# Generated by Django 3.2.12 on 2022-03-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_database_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allostructure',
            name='pdb_file',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='domain_pdb_file',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='mapped_pdb_file',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='pdb_file',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='raw_pdb_file',
        ),
    ]
